### ISSUE TITLE
Feature request.  SAP RFC & JSON

### ISSUE THREAD

**Issue by RickGanKL** [huysentruitw/SapNwRfc#22]
It is possible to call SAP RFC in JSON format. Just like the way Pyrfc calls.
Thank you!

**Comment by huysentruitw** [comment]
Since it is possible to define your own input and output models, which you can then use in combination with an ASP.NET Core API Controller or JsonSerializer, I'm not sure if I understand your question. Can you elaborate a little more and explain why serializing the models or using them in combination with ASP.NET Core doesn't fit your usecase?

**Comment by RickGanKL** [comment]
Thank you for your reply.
I am just so tired of writing the models.
English is not my native language.
